// <auto-generated />
using Baraja2_juangonzales.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Baraja2_juangonzales.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20211020014033_AddModel")]
    partial class AddModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Baraja2_juangonzales.Models.Naipe", b =>
                {
                    b.Property<string>("NaipeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ImagenUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NaipeId");

                    b.ToTable("Naipe");
                });
#pragma warning restore 612, 618
        }
    }
}
